### ISSUE TITLE
Support time units

### ISSUE THREAD

**Issue by tvrg** [FACT-Finder/perfably#12]
Graphs should indicate the unit of the y-axis (s, ms, ...).

At best this would be configurable:
For search requests a millisecond resolution makes sense. But for imports it might be a bit noisy.

For that Perfably must also know the unit of the raw data. I see three options:

1. Define that all metrics posted to Perfably must have a specific unit, e.g. milliseconds. Then the caller would have to convert metrics with other units before posting them.
2. Specify the unit per metric while posting to Perfably. We could default to `ms` and make the scheme flexible:
    ```json
    {
      "vedes.star_search.avg": {
        "unit": "s",
        "value": "2"
      },
      "bergfreunde.star_search.avg": 3
    }
    ```
2. Configure the unit per metric in `config.yml`, with default to `ms`:
    ````yaml
    charts:
      - name: chart name
        unit: s
        metrics:
            - name: metric1
              unit: ms
            - metric2
    ````

One problem with all time unit defaults is that we also want to display different data than time: Number of tests, loc, etc.
